### PR TITLE
[#2102] Cannot read properties of undefined (reading 'accountId')

### LINKED ISSUE #2102: Cannot read properties of undefined (reading 'accountId')
### Description

When I try to set proxies for the network I get the following error `Cannot read properties of undefined (reading 'accountId')`

### Steps to reproduce

1. Set proxies in that way how it's described in the example
2. Execute the example and get the receipt of transaction

Example:
```
import { Client, AccountId, PrivateKey, Hbar, TransferTransaction} from "@hashgraph/sdk"
import dotenv from 'dotenv'

dotenv.config();

const main = async () => {
    const nodes = {
        "34.94.106.61:50211": new AccountId(3),
        "50.18.132.211:50211": new AccountId(3),
        "35.237.119.55:50211": new AccountId(4),
        "3.212.6.13:50211": new AccountId(4),
        "35.245.27.193:50211": new AccountId(5),
        "52.20.18.86:50211": new AccountId(5),
    };

    const originAccountId = AccountId.fromString(process.env.OPERATOR_ID);
    const privateKey = PrivateKey.fromStringED25519(process.env.OPERATOR_KEY);
    const targetAccountId = AccountId.fromString(process.env.TARGET_ID);

    const client = Client.forNetwork(nodes)
    client.setOperator(originAccountId, privateKey);

    const validHbar = (hbars) => {
        return typeof hbars == "number"
        ? new Hbar(hbars.toFixed(6))
        : new Hbar(Number(hbars).toFixed(6));
    };

    const hbarAmount = validHbar(2);
    const txResponse = new TransferTransaction()
        .setMaxTransactionFee(new Hbar(5))
        .addHbarTransfer(originAccountId, hbarAmount.negated())
        .addHbarTransfer(targetAccountId, hbarAmount)
        .freezeWith(client);
    console.log("executing transaction...");
    const txSubmit = await txResponse.execute(client);
    const receipt = await txSubmit.getReceipt(client);
    console.log("Receipt:", receipt);
    client.close()
};

main();
```

### Additional context

_No response_

### Hedera network

testnet

### Version

v2.40.0

### Operating system

None

### PR DESCRIPTION
**Pull request by svetoslav-nikol0v**
**Description**:

Add a node to the selected nodes if only it hasn't been added already

Fixes #2102

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: src/client/ManagedNetwork.js [hunk 1]
```diff
@@ -206,17 +206,26 @@ export default class ManagedNetwork {
...
+        count = Math.min(count, healthyNodes.length);
+
         for (let i = 0; i < count; i++) {
+            // Select a random index
             const nodeIndex = Math.floor(Math.random() * healthyNodes.length);
             const selectedNode = healthyNodes[nodeIndex];
+
+            // Check if the node exists
+            if (!selectedNode) {
+                console.error("Selected an undefined node. Index:", nodeIndex);
```
Comment (ochikov) [inline src/client/ManagedNetwork.js:221]: Do we need to log in here? Let's put a logger with an appropriate level of debugging.

**Review by ochikov — CHANGES_REQUESTED** [review]

**Review by agadzhalov — APPROVED** [review]
LGTM

**Review by ochikov — APPROVED** [review]
