### PR TITLE
fix: serialize deserialize FileAppend

### LINKED ISSUE #2167: FileAppendTransaction incorrect content after deserialization
### Description

Serializing and then deserializing a FileAppendTransaction causes incorrect content to be set.
After the deserialization, the content is sliced to the chunk size.
Ex. If you have a content length of 100_000 after the deserialization, the content will consist only of the first {chunkSize} bytes.

### Steps to reproduce

1. Run this snippet
```
const { FileAppendTransaction } = require('@hashgraph/sdk');

async function run() {
  const contentLength = 632421;
  const content = generateUInt8Array(contentLength);

  const transaction = new FileAppendTransaction()
    .setTransactionValidDuration(180)
    .setContents(content);

  console.log(transaction.contents.length); //632421 (content length)

  const transactionBytes = transaction.toBytes();

  const transactionFromBytes =
    FileAppendTransaction.fromBytes(transactionBytes);

  console.log(transactionFromBytes.contents.length); //4096 (default chunk size)
}
run();

function generateUInt8Array(length) {
  const uint8Array = new Uint8Array(length);

  for (let i = 0; i < length; i++) {
    uint8Array[i] = Math.floor(Math.random() * 256);
  }

  return uint8Array;
}
```

### Additional context

_No response_

### Hedera network

other

### Version

v2.42.0-beta.4

### Operating system

None

### PR DESCRIPTION
**Pull request by ivaylonikolov7**
**Description**:
Implement chunk logic for toBytes method and disallow addSignature function until the next release. 

Fixes #2167 #2536

**Notes for reviewer**:
There should be refactoring done. We need to implement `ChunkTransaction`. This fix is more like a patch before the major refactor for ChunkedTransaction like the other SDKs. 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by 0xivanov — DISMISSED** [review]
LGTM

File: test/integration/FileAppendIntegrationTest.js
Comment (gsstoykov) [inline test/integration/FileAppendIntegrationTest.js:1]: Since this functionality is flaky from past experience, try creating more integration tests IMHO no need to revisit this issue.

File: src/file/FileAppendTransaction.js [hunk 1]
```diff
@@ -445,6 +457,90 @@ export default class FileAppendTransaction extends Transaction {
         return "fileAppend";
     }
 
+    /**
+     * Build all the transactions when transacgtions are not signed
+     * @override
+     * @internal
+     */
+    _buildIncompletedTransactions() {
```
Comment (gsstoykov) [inline src/file/FileAppendTransaction.js:465]: nit: *Incomplete

File: test/integration/FileAppendIntegrationTest.js [hunk 2]
```diff
@@ -211,7 +215,67 @@ describe("FileAppend", function () {
         ).getReceipt(env.client);
     });
 
+    it("should keep content after deserialization", async function () {
+        this.timeout(120000);
```
Comment (gsstoykov) [inline test/integration/FileAppendIntegrationTest.js:219]: I really don't like that we have to do this every single time. Consider working around this or making it configurable.

Comment (gsstoykov) [reply test/integration/FileAppendIntegrationTest.js:219]: Maybe create an issue for it?

File: src/file/FileAppendTransaction.js [hunk 3]
```diff
@@ -445,6 +457,90 @@ export default class FileAppendTransaction extends Transaction {
...
+
+            nextTransactionId = new TransactionId(
+                /** @type {AccountId} */ (nextTransactionId.accountId),
+                new Timestamp(
+                    /** @type {Timestamp} */ (
+                        nextTransactionId.validStart
+                    ).seconds,
+                    /** @type {Timestamp} */ (
+                        nextTransactionId.validStart
+                    ).nanos.add(1),
```
Comment (gsstoykov) [inline src/file/FileAppendTransaction.js:509]: Is this adding one nanosecond? Why don't you just generate a transaction id here?

File: src/transaction/Transaction.js [hunk 4]
```diff
@@ -800,6 +810,11 @@ export default class Transaction extends Executable {
         const isSingleSignature = signature instanceof Uint8Array;
         const isArraySignature = Array.isArray(signature);
 
+        if (this.getRequiredChunks() > 1) {
+            throw new Error(
+                "Add signature is not supported for chunked transactions",
+            );
+        }
```
Comment (gsstoykov) [inline src/transaction/Transaction.js:817]: What if you have a ChunkedTransacrtion with one chunk?

Comment (ivaylonikolov7) [reply src/transaction/Transaction.js:817]: Just added an integration test for this case. I think it works properly as of right now but it will probably going to get thoroughly tested in the new version when we have to add the signature functionality for file append too.

File: src/file/FileAppendTransaction.js (hunk 3 above)
Comment (ivaylonikolov7) [reply src/file/FileAppendTransaction.js]: Hm, refactored this to generating `TransactionId` - `TransactionId.generate(dummyAccountId);`. You meant like this, right?

File: test/integration/FileAppendIntegrationTest.js
Comment (ivaylonikolov7) [reply test/integration/FileAppendIntegrationTest.js:1]: I added a bunch of inttegration tests. If you think it's missing some I am open to adding them. I agree that the functionality is flaky.

File: test/integration/FileAppendIntegrationTest.js (hunk 2 above)
Comment (ivaylonikolov7) [reply test/integration/FileAppendIntegrationTest.js:220]: We can work around this by editing the Taskfile that runs the integration tests.

File: src/file/FileAppendTransaction.js (hunk 1 above)
Comment (ivaylonikolov7) [reply src/file/FileAppendTransaction.js:465]: Hm, I changed it but now that I think about it shouldn't it be `Incompleted`? :D

File: src/file/FileAppendTransaction.js (hunk 3 above)
Comment (gsstoykov) [reply src/file/FileAppendTransaction.js]: The dummyAccountId is just a temp value. Why not `TransactionId.generate(nextTransactionId.accountId);` ? Or that won't work for your use case.

File: src/transaction/Transaction.js (hunk 4 above)
Comment (gsstoykov) [reply src/transaction/Transaction.js:817]: Where is this integration test? Couldn't find...

Comment (gsstoykov) [reply src/transaction/Transaction.js:817]: my bad nvm

Comment (ivaylonikolov7) [reply src/transaction/Transaction.js:817]: `FileAppendIntegrationTest.js` - "should be able to sign transaction with 1 chunk"

**Review by gsstoykov — APPROVED** [review]

**Review by agadzhalov — APPROVED** [review]
LGTM
