### PR TITLE
fix: `Query.queryPayment`, `Query.maxQueryPayment`, and `Client.maxQueryPayment` interactions

### LINKED ISSUE #1230: Fix `Query.[queryPayment|maxQueryPayment]` and `Client.maxQueryPayment` interactions
The current interactions of the aforementioned fields are a bit obscure and confusing. We should clean up the code around that and make sure we adequately test it so it's easier to understand.

### PR DESCRIPTION
**Pull request by danielakhterov**
**Description**:

**Related issue(s)**:

Fixes #1230 

**Notes for reviewer**:

**Checklist**

- [X] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

### CODE REVIEW

File: src/query/Query.js [hunk 1]
```diff
@@ -336,64 +336,63 @@ export default class Query extends Executable {
         // - Query the cost, and compare it to `client.maxQueryPayment`
         //
         // TODO: Create a test that matches this table
```
Comment (SimiHunjan) [inline src/query/Query.js:338]: Is this still a TODO or does it need to be removed?

**Review by SimiHunjan — APPROVED** [review]

**Review by mehcode — APPROVED** [review]
