### PR TITLE
fix: `TokenUpdateTransaction.pauseKey`

### LINKED ISSUE #1221: `pauseKey` does not update with `TokenUpdateTransaction` because its missing from `_makeTransactionData`
### Description

Sent `TokenUpdateTransaction` with `setPauseKey` to a newly created token. The tx was `SUCCESSFUL` but the `pauseKey` kept the old value and did not update as expected.

### Steps to reproduce

image

Looking at the SDK, the `pauseKey` is missing from `_makeTransactionData` [here](https://github.com/hashgraph/hedera-sdk-js/blob/main/src/token/TokenUpdateTransaction.js#L653)

### Additional context

_No response_

### Hedera network

testnet

### Version

v2.17.1

### Operating system

macOS

### PR DESCRIPTION
**Pull request by danielakhterov**
Signed-off-by: Daniel Akhterov <akhterovd@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #1221

**Notes for reviewer**:

**Checklist**

- [X] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

### CODE REVIEW

File: test/unit/TokenUpdateTransaction.js [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+            )
+            .setTokenName("name")
+            .setTokenSymbol("symbol")
+            .setTokenMemo("memo")
+            .setTreasuryAccountId(treasuryAccountId)
+            .setAutoRenewAccountId(autoRenewAccountId)
+            .setAdminKey(key1)
+            .setKycKey(key2)
+            .setFreezeKey(key3)
+            .setPauseKey(key4)
```
Comment (mgarbs) [inline test/unit/TokenUpdateTransaction.js:37]: Curious why we are using the same keys to update that we used to create? I get why the `adminKey` will be the same but.. If these are all the same keys, then we can't know for sure if their values updated. We could mix up all the keys and check for their updated values in expect to get a more encompassing test that `TokenUpdateTransaction` checks out.

Comment (danielakhterov) [reply test/unit/TokenUpdateTransaction.js:37]: This is strictly a serialization test; it asserts that if a user sets keys using `set*Key()` then when we generate the protobuf the keys are set accordingly. For instance if a user calls `setPauseKey(key4)` then in the protobuf we should expect `tokenUpate.pauseKey.ed25519` to be set to the same bytes as `key4.publicKey.toBytesRaw()`. This test would catch still mistakes like missing `pauseKey` in the `_makeTransactionData()`

Comment (mgarbs) [reply test/unit/TokenUpdateTransaction.js:37]: Okay got it that makes sense
