### PR TITLE
fix: handle nullable gas and amount in ContractFunctionResult when ContractCallLocal is passed

### LINKED ISSUE #1208: Handle nullable gas and amount in ContractFunctionResult when ContractCallLocal is passed
### Description

When mapping the `ContractCallLocal` response to the `ContractFunctionResult`, the following error has been thrown
```
/home/.nvm/versions/node/v16.14.2/bin/node --require ts-node/register /home/Desktop/hethers.js/obsolete/example.ts
/home/Desktop/hethers.js/node_modules/long/src/long.js:286
    return fromBits(val.low, val.high, typeof unsigned === 'boolean' ? unsigned : val.unsigned);
                        ^
TypeError: Cannot read properties of undefined (reading 'low')
    at Function.fromValue (/home/Desktop/hethers.js/node_modules/long/src/long.js:286:25)
    at Function._fromProtobuf (/home/Desktop/hethers.js/node_modules/@hashgraph/sdk/lib/contract/ContractFunctionResult.cjs:196:63)
    at ContractCallQuery._mapResponse (/home/Desktop/hethers.js/node_modules/@hashgraph/sdk/lib/contract/ContractCallQuery.cjs:307:60)
    at ContractCallQuery.execute (/home/Desktop/hethers.js/node_modules/@hashgraph/sdk/lib/Executable.cjs:703:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sdk (/home/Desktop/hethers.js/obsolete/example.ts:107:17)
    at async init (/home/Desktop/hethers.js/obsolete/example.ts:113:12)
```
### Steps to reproduce

```typescript
const from = "0.0.1002";
const nodeID = AccountId.fromString(asAccountString('0.0.3'));
const paymentTxId = TransactionId.generate(from);

const hederaTx = new ContractCallQuery()
    .setFunctionParameters(arrayify('0xcfae3217'))
    .setNodeAccountIds([nodeID])
    .setGas(300000)
    .setPaymentTransactionId(paymentTxId)
    .setContractId("0.0.1064");

const baseCost = 1430834130;
const cost = 1460834130;
const paymentBody = {
    transactionID: paymentTxId._toProtobuf(),
    nodeAccountID: nodeID._toProtobuf(),
    transactionFee: Hbar.fromTinybars(baseCost).toTinybars(),
    transactionValidDuration: {
        seconds: Long.fromInt(120),
    },
    cryptoTransfer: {
        transfers: {
            accountAmounts: [
                {
                    accountID: AccountId.fromString(from)._toProtobuf(),
                    amount: Hbar.fromTinybars(cost).negated().toTinybars()
                },
                {
                    accountID: nodeID._toProtobuf(),
                    amount: Hbar.fromTinybars(cost).toTinybars()
                }
            ],
        },
    },
};

const signed = {
    bodyBytes: TransactionBody.encode(paymentBody).finish(),
    sigMap: {}
};
const walletKey = PrivateKey.fromStringECDSA('0x6ec1f2e7d126a74a1d2ff9e1c5d90b92378c725e506651ff8bb8616a5c724628');
const signature = walletKey.sign(signed.bodyBytes);
signed.sigMap = {
    sigPair: [walletKey.publicKey._toProtobufSignature(signature)]
}

const transferSignedTransactionBytes = SignedTransaction.encode(signed).finish();
hederaTx._paymentTransactions.push({
    signedTransactionBytes: transferSignedTransactionBytes
});

const provider = hethers.providers.getDefaultProvider('local');
const callRes = await hederaTx.execute(provider.getHederaClient());

console.log(callRes.bytes.toString('utf8'));
```
### Additional context

_No response_

### Hedera network

other

### Version

2.17.0

### Operating system

Linux

### PR DESCRIPTION
**Pull request by natanasow**
Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #1208

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: src/contract/ContractFunctionResult.js [hunk 1]
```diff
@@ -57,8 +57,8 @@ export default class ContractFunctionResult {
      * @param {ContractId[]} result.createdContractIds
      * @param {Uint8Array | null} result.evmAddress
      * @param {Uint8Array} result.bytes
-     * @param {Long} result.gas
-     * @param {Long} result.amount
+     * @param {Long|null} result.gas
+     * @param {Long|null} result.amount
```
Comment (danielakhterov) [inline src/contract/ContractFunctionResult.js:61]: Unfortunately, this is a breaking change. :( Would it be reasonable to perhaps use `Long.fromNumber(-1)` to represent a `null`? I would prefer using `null`, but we can't make breaking changes.

**Review by danielakhterov — APPROVED** [review]
